INSERT INTO interactions (user_id, media_id, rating) 
VALUES 
(1, 1, 'like'),
(1, 2, 'interest'),
(1, 3, 'dislike'),
(1, 4, 'meh'),
(2, 2, 'interest'),
(3, 1, 'meh'),
(3, 1, 'dislike'),
(4, 5, 'interest'),
(4, 7, 'like'),
(4, 9, 'dislike'),
(5, 1, 'dislike'),
(5, 8, 'like'),
(5, 2, 'meh'),
(6, 7, 'interest'),
(7, 7, 'meh'),
(8, 8, 'dislike'),
(9, 1, 'like'),
(10, 1, 'dislike');