INSERT INTO friends (sending_user_id, recieving_user_id, friendship, friendship_pending) 
VALUES 
(1, 2, true, false),
(1, 8, true, false),
(1, 9, true, false),
(2, 3, false, true),
(2, 9, true, false),
(3, 1, true, false),
(3, 2, true, false),
(4, 1, false, true),
(4, 5, false, true),
(4, 6, true, false),
(4, 7, false, true),
(4, 10, false, false),
(5, 1, true, false),
(5, 11, true, false),
(5, 17, true, false),
(5, 3, true, false),
(5, 4, true, false),
(5, 15, true, false),
(5, 16, true, false),
(5, 12, true, false),
(5, 18, true, false),
(7, 1, true, false),
(8, 4, true, false),
(10, 1, false, false),
(10, 4, false, true),
(18, 5, true, false);
