INSERT INTO friends (sending_user_id, recieving_user_id, friendship, friendship_pending) 
VALUES 
(1, 2, true, false),
(2, 9, true, false),
(7, 1, true, false),
(2, 3, false, true),
(3, 1, true, false),
(1, 9, true, false),
(5, 4, true, false),
(3, 2, true, false),
(4, 7, false, true),
(8, 4, true, false),
(10, 4, false, true),
(10, 1, false, false),
(4, 1, false, true),
(1, 8, true, false),
(11, 1, true, false),
(4, 6, false, true),
(5, 7, true, false),
(5, 8, true, false),
(6, 8, true, false),
(6, 9, true, false),
(6, 10, true, false),
(6, 11, true, false),
(6, 3, true, false),
(5, 2, true, false);
