DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created DATE DEFAULT CURRENT_DATE NOT NULL,
  modified DATE DEFAULT CURRENT_DATE NOT NULL
);